#!/bin/bash
#
# Runs at the end of git flow release start
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the release prefix)
# $4    The base from which this release is started
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
VERSION=$1
ORIGIN=$2
BRANCH=$3
BASE=$4

if which mversion 1>&2 > /dev/null; then
  mversion patch >> /dev/null
  mversion | awk '{ print $2 }' | uniq > VERSION

  test -f bower.json    && git add bower.json
  test -f composer.json && git add composer.json
  test -f package.json  && git add package.json

  git add VERSION
  git commit -q -m "Préparation de la version $(cat VERSION | sed 's/^v//')"
fi

exit 0
