#!/usr/bin/env sh

# Prompt Colors {{{
C_GREEN="\[\033[01;32m\]"
C_BLUE="\[\033[01;34m\]"
C_YELLOW="\[\033[0;33m\]"
C_NONE="\[\033[00m\]"
# }}}

# Prompt Customization
function parse_git_branch {
  test "${HOME}" != "${PWD}"    || return
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
    echo "("${ref#refs/heads/}") "
}

PS1="$C_GREEN\u@\h $C_BLUE\W $C_YELLOW\$(parse_git_branch)$C_BLUE\$ $C_NONE"

# Tmux Powerline
PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#I_#P") "$PWD")'

# vim:foldmethod=marker:foldlevel=0
