#!/usr/bin/env bash

export SYMFONY_ASSETS_INSTALL="relative"

__php_wrapper() {
  GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)

  # check if a docker-compose.yml is present
  if [ -f "$GIT_ROOT/docker-compose.yml" ]; then
    PHP_CONTAINER=$(docker-compose ps | grep '_php_' | awk '{ print $1 }')
    docker exec -u $(id -u) -it $PHP_CONTAINER php $@ 2> /dev/null || >&2 echo "$@: Command failed ($PHP_CONTAINER)"
  else
    php $@
  fi

}

sf() {
  ARGS="$@"
  GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
  CONSOLE=$(git ls-files $GIT_ROOT/app/console 2>/dev/null) || (echo 'This is not a Symfony repository' 1>&2 && exit 1)

  __php_wrapper ${CONSOLE} ${ARGS}
}
