#!/usr/bin/env bash

# Optimisations for WINE 
export WINEDEBUG=-all




# Shortcuts for EVE

eve() {
	WINE_PREFIX_EVE=${WINE_PREFIX_EVE:-~/.wine}
	case "$1" in
		"")
			echo "Launching EVE..."
			WINEPREFIX=$WINE_PREFIX_EVE wine start 'C:\Program Files (x86)\CCP\EVE\eve.exe'
			;;
	  "config")
			echo "Launching EVE wine configuration..."
			WINEPREFIX=$WINE_PREFIX_EVE winecfg
			;;
	esac
}
