#!/usr/bin/env bash

# Optimisations for WINE 
export WINEDEBUG=-all




# Shortcuts for EVE

eve() {
	WINEPREFIX_EVE=${WINEPREFIX_EVE:-~/.wine}
	case "$1" in
		"")
			echo "Launching EVE..."
			WINEPREFIX=$WINEPREFIX_EVE wine start 'C:\Program Files (x86)\CCP\EVE\eve.exe'
			;;
	  "config")
			echo "Launching EVE wine configuration..."
			WINEPREFIX=$WINEPREFIX_EVE winecfg
			;;
	esac
}
