#!/usr/bin/env sh
ARGS="$@"
GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
CONSOLE=$(git ls-files $GIT_ROOT/app/console 2>/dev/null) || (echo 'This is not a Symfony repository' 1>&2 && exit 1)
eval "${CONSOLE} ${ARGS}"
