#!/bin/env sh

# Remove all aliases {{{
unalias -a
# }}}

# Easier navigation {{{
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
# }}}

# Listing files {{{
alias ls="ls --color=auto"
alias ll="ls -lh"
alias l="ls -lha"
# }}}

# Convenient aliases {{{
alias map="xargs -n1"
alias open="xdg-open"
# }}}

# Program Aliases {{{
command -v tmux > /dev/null 2>&1 && {
  alias tmux="tmux -2"
}
command -v docker-compose > /dev/null 2>&1 && {
  alias dc="docker-compose"
}
# }}}

# Git + Hub {{{
command -v 'hub' >/dev/null 2>&1 && {
  $(`command -v 'hub'` alias -s)
}
# }}}

# Pass alias to sudo {{{
alias sudo='sudo '
# }}}

# Sudoed commands {{{
(groups | grep -q wheel) && command -v sudo > /dev/null 2>&1 && {
    SUDO_CMDS=""

        # Gentoo Administrative Commands {{{
        command -v emerge > /dev/null 2>&1 && {
            SUDO_CMDS+="emerge layman euse eix-sync
                       rc-update etc-update eix-update
                       revdep-rebuild emaint
                       dispatch-conf"
        }
        # }}}

    for cmd in $SUDO_CMDS; do
        command -v $cmd >/dev/null 2>&1 && alias $cmd="sudo ${cmd}";
    done;
}
# }}}

# vim:foldmethod=marker:foldlevel=0
