#!/bin/env sh

# Path functions {{{
    path_append ()  { path_remove $1; export PATH="$1:$PATH"; }
    path_prepend () { path_remove $1; export PATH="$PATH:$1"; }
    path_remove ()  { export PATH=`echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`; }
# }}}

function reload {
    source ~/.bashrc
}

function session_type {
  SESSION_TYPE=local
  ([ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]) && SESSION_TYPE=remote/ssh;
  ([ -f /proc/1/cgroup ] && grep ':\/docker\/[a-z0-9]*$' /proc/1/cgroup > /dev/null  ) && SESSION_TYPE=remote/docker;
  echo -e $SESSION_TYPE
}

command_not_found_handle() {
  if [[ $(session_type) == "remote/docker" ]]; then
    echo "$0: $1: command not found"
    return
  fi

  docker_exec "$@"
}

kernel-update() {
	KERNEL_NAME=$(eselect kernel show | grep /usr/src/linux | sed -e 's@\s*/usr/src/linux-@@')
	KERNEL_GISTID=${KERNEL_GISTID:-57185c0962633cc43ce9}

	echo Building kernel $KERNEL_NAME
	sudo sh <<- EOF
		zcat /proc/config.gz > /usr/src/linux/.config
		cd /usr/src/linux
		make
		make modules_install
		mount /boot
		make install
		dracut -H '' $KERNEL_NAME
		grub2-mkconfig -o /boot/grub/grub.conf
		umount /boot
	EOF
	cat /usr/src/linux/.config | gist -u $KERNEL_GISTID -f config
}

json() {
	if [ -t 0 ]; then # argument
		python -mjson.tool <<< "$*" | pygmentize -l javascript
	else # pipe
		python -mjson.tool | pygmentize -l javascript
	fi
}
# vim:foldmethod=marker:foldlevel=0
