#!/bin/env sh

# Path functions {{{
    path_append ()  { path_remove $1; export PATH="$1:$PATH"; }
    path_prepend () { path_remove $1; export PATH="$PATH:$1"; }
    path_remove ()  { export PATH=`echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`; }
# }}}

function reload {
    source ~/.bashrc
}

function session_type {
  SESSION_TYPE=local
  ([ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]) && SESSION_TYPE=remote/ssh;
  ([ -f /proc/1/cgroup ] && grep ':\/docker\/[a-z0-9]*$' /proc/1/cgroup > /dev/null  ) && SESSION_TYPE=remote/docker;
  echo -e $SESSION_TYPE
}

json() {
	if [ -t 0 ]; then # argument
		python -mjson.tool <<< "$*" | pygmentize -l json
	else # pipe
		python -mjson.tool | pygmentize -l json
	fi
}
# vim:foldmethod=marker:foldlevel=0
