#!/bin/sh

sf() {
  ARGS="$@"
  GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
  CONSOLE=$(git ls-files $GIT_ROOT/app/console 2>/dev/null) || (echo 'This is not a Symfony repository' 1>&2 && exit 1)

  docker_compose_wrapper php -d memory_limit=-1 ${CONSOLE} ${ARGS}
}


phpunit() {
  docker_compose_wrapper php -d memory_limit=-1 bin/phpunit $@
}

composer() {
  COMPOSER_HOME=${COMPOSER_HOME:-$HOME/.composer} docker_compose_wrapper php -d memory_limit=-1 /usr/local/bin/composer $@
}
