#!/usr/bin/env bash
function prompt_git_branch {
  test "${HOME}" != "${PWD}" || return
  ref=$(git symbolic-ref HEAD 2>/dev/null) || return
  echo ""${ref#refs/heads/}" "
}

function prompt_project_version {
  test "${HOME}" != "${PWD}" || return
  dir=$(git rev-parse --show-toplevel 2>/dev/null) || return
  ([ -f "${dir}/VERSION" ] && echo $(cat "${dir}/VERSION")) || return
}

function prompt_session {
  case $(session_type) in
    remote/*)
      echo -e "\u@\h"
      ;;
    *)
      echo -e "\u"
      ;;
  esac;
}

# ( x=`tput op` y=`printf %$((${COLUMNS}-6))s`;for i in {0..256};do o=00$i;echo -e ${o:${#o}-3:3} `tput setaf $i;tput setab $i`${y// /=}$x;done; )

function prompt {
  colors=$(tput colors)

  if (($colors >= 256)); then
    local BG_DARK_GREY="\[$(tput setab 234)\]"
    local FG_DARK_GREY="\[$(tput setaf 234)\]"

    local BG_GREY="\[$(tput setab 237)\]"
    local FG_GREY="\[$(tput setaf 237)\]"

    local BG_LIGHT_GREY="\[$(tput setab 240)\]"
    local FG_LIGHT_GREY="\[$(tput setaf 240)\]"

    local BG_BLUE="\[$(tput setab 25)\]"
    local FG_BLUE="\[$(tput setaf 25)\]"

    local BG_RED="\[$(tput setab 124)\]"
    local FG_RED="\[$(tput setaf 124)\]"

    local C_RESET="\[\e[0m\]"

    local S_ARROW=""
  fi

  if [[ $ASCIINEMA_REC == "1" ]]; then
    export PROMPT_DIRTRIM=1;
    export PS1="${FG_BLUE}\w${FG_LIGHT_GREY} $ ${C_RESET}";
    return;
  fi

  local PROMPT_SESSION=$(prompt_session);
  case $(prompt_session_type) in
    remote/ssh)
      PROMPT_SESSION=" ${PROMPT_SESSION}"
      ;;
    remote/docker)
      PROMPT_SESSION="© ${PROMPT_SESSION}"
      ;;
  esac

  if [ "$UID" == 0 ]; then
    local user="${C_RESET}${BG_RED} ${PROMPT_SESSION} ${BG_GREY}${C_RESET}${FG_RED}${S_ARROW}"
	elif [ "$UID" != 1000 ]; then
    local user="${BG_BLUE} ${PROMPT_SESSION} ${BG_LIGHT_GREY}${FG_BLUE}${S_ARROW}"
	else
		local user="${BG_LIGHT_GREY}"
	fi

  local cmd="${BG_LIGHT_GREY}${FG_DARK_GREY}\w ${BG_DARK_GREY}${FG_LIGHT_GREY}${S_ARROW}"
  local git_branch="${BG_DARK_GREY}${FG_LIGHT_GREY}\$(prompt_git_branch)${C_RESET}${BG_LIGHT_GREY}${FG_DARK_GREY}${S_ARROW}\$(prompt_project_version)${C_RESET}${FG_LIGHT_GREY}${S_ARROW}${C_RESET}"

  if (($colors >= 256)); then
    export PS1="${C_RESET}${user} ${cmd} ${git_branch} ${C_RESET}";
  fi
}

prompt

# vim:foldmethod=marker:foldlevel=0
