#!/usr/bin/env bash

# Optimisations for WINE
export WINEDEBUG=-all
#export LD_PRELOAD="libpthread.so.0 libGL.so.1"
export __GL_THREADED_OPTIMIZATIONS=0
export __GL_SYNC_TO_VBLANK=1
export __GL_YIELD="NOTHING"
export CSMT=enabled

# Shortcuts for EVE
eve() {
	local WINEPREFIX_EVE=${WINEPREFIX_EVE:-~/.local/share/wineprefixes/eve}
	local WINEDLLOVERRIDES_EVE=${WINEDLLOVERRIDES:-"msvcr80,msvcr90,msvcr100=b,n"}

	case "$1" in
		"")
			echo "Launching EVE"
			WINEARCH=win32 WINEPREFIX=$WINEPREFIX_EVE wine start 'C:\Program Files\CCP\EVE\bin\exefile.exe'
			;;
		"launcher")
			echo "Launching EVE launcher"
			WINEARCH=win32 WINEPREFIX=$WINEPREFIX_EVE wine start 'C:\Program Files\CCP\EVE\eve.exe'
			;;
	  "repair")
			echo "Launching EVE repair tool"
			WINEARCH=win32 WINEPREFIX=$WINEPREFIX_EVE wine start 'C:\Program Files\CCP\EVE\repair.exe'
			;;
		"setup")
			echo "Winetricks setup"
			WINEARCH=win32 WINEPREFIX=$WINEPREFIX_EVE winetricks vcrun2005 vcrun2008 vcrun2010 corefonts win7
			;;

	  "config")
			echo "Launching EVE wine configuration..."
			WINEARCH=win32 WINEPREFIX=$WINEPREFIX_EVE winecfg
			;;
	esac
}

gp6() {
 local WINEPREFIX_GP6=${WINEPREFIX_GP6:-~/.local/share/wineprefixes/gp}

	case "$1" in
		"update")
			echo "Launching Guitar Pro 6 updater"
			WINEPREFIX=$WINEPREFIX_GP6 wine start 'C:\Program Files\Guitar Pro 6\GPUpdater.exe'
			;;
		"setup")
			echo "Winetricks setup"
			WINEPREFIX=$WINEPREFIX_GP6 winetricks vcrun2005 vcrun2008 vcrun2010 corefonts win7
			;;
	  "config")
			echo "Launching Guitar Pro 6 wine configuration..."
			WINEPREFIX=$WINEPREFIX_GP6 winecfg
	    ;;
		*)
			echo "Launching Guitar Pro 6"
			local FILE=$1	
			if [[ $FILE ]]; then
				FILE="'$(pwd)/$*'"
			fi
			WINEPREFIX=$WINEPREFIX_GP6 wine start 'C:\Program Files\Guitar Pro 6\GuitarPro.exe' $FILE
			;;
	esac
}

